name: Build and test
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: yarn install
    - name: Install slither
      run: pip3 install -r scripts/requirements.txt
    - name: Show slither version
      run: slither --version
    - name: lint
      run: yarn fullcheck
