name: Build and test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install project
      run: yarn install
    - name: Install slither
      run: pip3 install -r scripts/requirements.txt
    - name: Show slither version
      run: slither --version
    - name: lint
      run: yarn fullcheck
    - name: Test deployment
      run: ./scripts/test_deploy.sh
    - name: Run tests
      run: yarn test
